main/fittoapp/urls.py
from django.urls import path
from . import views

app_name = 'fittoapp'
urlpatterns = [
    path("", views.index, name="index"),
    path("calorie", views.calorie, name="calorie"),
    path("activity", views.activity, name="activity"),
    path("foodentry", views.foodentry, name="foodentry"),
    path("activityentry",  views.activityentry, name="acitivityentry")
]

main/main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', users_views.register_request, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path('logout/', users_views.logout_request, name="logout"),
    path("", include('fittoapp.urls'))
]

main/fittoapp/models.py
from django.db import models
from users.models import User
from datetime import date
# Create your models here.

today = date.today()

class FoodDiary(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="user", related_name="food")
    energy = models.IntegerField(null=True, default=0)
    protein = models.IntegerField(null=True, default=0)
    carbs = models.IntegerField(null=True, default=0)
    fat = models.IntegerField(null=True, default=0)
    fiber = models.IntegerField(null=True, default=0)
    breakfast = models.IntegerField(null=True, default=0)
    lunch = models.IntegerField(null=True, default=0)
    dinner = models.IntegerField(null=True, default=0)
    date = models.DateField(null=True, default=f"{today.year}-{today.month}-{today.day}")

    def __str__(self):
        return f"{self.user} ate {self.energy}kcal, protein: {self.protein}, carbs: {self.carbs}, fat: {self.fat}, fiber: {self.fiber} on {self.date}. Breakfast: {self.breakfast}, Lunch: {self.lunch}, Dinner: {self.dinner}"

    
class UserBodyReq(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="user", related_name="bodyreq")
    bmr = models.IntegerField(null=True)
    tdee = models.IntegerField(null=True)
    daily_intake = models.IntegerField(null=True)

    def __str__(self):
        return f"{self.user.email} has a BMR of {self.bmr}, a TDEE of {self.tdee} and daily intake of {self.daily_intake} kcal"
    
class ActivityDiary(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="user", related_name="activitydone")
    activity_done = models.CharField(max_length=50, null=True)
    calories_burned = models.IntegerField(null=True, default=0)
    date = models.DateField(null=True, default=f"{today.year}-{today.month}-{today.day}")

    def __str__(self):
        return f"{self.user.email} did {self.activity_done} and burned {self.calories_burned} on {self.date}"
    

main/fittoapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.core import serializers
from django.db.models import Avg
from fittoapp.models import FoodDiary, UserBodyReq, ActivityDiary
from users.models import User
import json
from datetime import date

# Create your views here.

today = date.today()
today_string = f"{today.year}-{today.month}-{today.day}"

def index(request):
        if not request.user.is_authenticated:
                return redirect('login')
        u = User.objects.get(pk=request.user.id)
        # food data
        create = FoodDiary.objects.get_or_create(date=today_string, user=u)
        food_data = FoodDiary.objects.filter(date=today_string, user=u)
        food_data_aggregate = FoodDiary.objects.filter(user=u)
        activity_data = ActivityDiary.objects.filter(date=today_string, user=u)
    
        food_data_energy = food_data_aggregate.values('energy', 'date')
        #user body requirements data
        b = UserBodyReq.objects.filter(user=u)

        food_data_energy_list = []
        food_data_date_list = []

        for energy in food_data_energy:
                food_data_energy_list.append(energy['energy'])
                food_data_date_list.append(energy['date'].strftime("%d"))
        #avg intakes
        avg_data = {
                'avgEnergy': food_data_aggregate.aggregate(Avg('energy')),
                'avgProtein': food_data_aggregate.aggregate(Avg('protein')),
                'avgCarbs': food_data_aggregate.aggregate(Avg('carbs')),
                'avgFat': food_data_aggregate.aggregate(Avg('fat')),
                'avgFiber': food_data_aggregate.aggregate(Avg('fiber')),
                'avgBreakfast': food_data_aggregate.aggregate(Avg('breakfast')),
                'avgLunch': food_data_aggregate.aggregate(Avg('lunch')),
                'avgDinner': food_data_aggregate.aggregate(Avg('dinner')),
                
        }

        #jsonify
        # food_data_energy_json = serializers.serialize("json", food_data_energy)

        bmr_data_json = serializers.serialize("json", b)
        food_data_json = serializers.serialize("json", food_data)
        activity_data_json = serializers.serialize("json", activity_data)

        avg_data_json = json.dumps(avg_data)
        food_data_energy_list_json = json.dumps(food_data_energy_list)
        food_data_date_list_json = json.dumps(food_data_date_list)
        return render(request, 'fittoapp/index.html', {
                "food_data": food_data_json,
                "bmr_data": bmr_data_json,
                "avg_data": avg_data_json,
                "food_data_energy": food_data_energy_list_json,
                "food_data_date": food_data_date_list_json,
                "activity_data": activity_data_json,
        })

@csrf_exempt
def foodentry(request):
        if request.method == 'POST':
                xml_bytesvalue = request.body
                data_decode = xml_bytesvalue.decode("utf-8").replace("'", '"')
                data = json.loads(data_decode)
                u = User.objects.get(pk=request.user.id)
                #retriving current macro values, default: 0
                p = FoodDiary.objects.get_or_create(date=today_string, user=u)
                print(p)
                print(data)
                # updating macro values
                energy = float(data['Energy']) + p[0].energy
                protein = float(data['Protein']) + p[0].protein
                carbs = float(data['Carbs']) + p[0].carbs
                fat = float(data['Fat']) + p[0].fat
                fiber = float(data['Fiber']) + p[0].fiber
                timeofday = data['timeofday']
                breakfast = 0
                lunch = 0
                dinner = 0
                print(timeofday)
                if timeofday == 'Breakfast':
                        breakfast = float(data['Energy']) + p[0].breakfast
                elif timeofday == 'Lunch':
                        lunch = float(data['Energy']) + p[0].lunch
                else: 
                        dinner = float(data['Energy']) + p[0].dinner
                obj, created = FoodDiary.objects.update_or_create(
                        user=u,
                        date=today_string,
                        defaults={"user":u, "energy": energy, "protein": protein, "carbs": carbs, "fat": fat, "fiber": fiber, 'breakfast': breakfast, 'lunch': lunch, 'dinner': dinner}
                )

                return HttpResponse("Success")
        return HttpResponse('failure')

@csrf_exempt
def activityentry(request):
        if request.method == 'POST':
                xhr_bytesvalue = request.body
                data_decode = xhr_bytesvalue.decode("UTF-8").replace("'", '"')
                data = json.loads(data_decode)
                u = User.objects.get(pk=request.user.id)
        
                activity_done = data['activity_done']
                calories_burned = data['calories_burned']

                p = ActivityDiary.objects.create(user=u, activity_done=activity_done, calories_burned=calories_burned, date=today_string)

                return HttpResponse("Success")
        return HttpResponse('failure')

def calorie(request):
        return render(request, 'fittoapp/calc.html')

def activity(request):
        return render(request, 'fittoapp/activity.html')

main/fittoapp/templates/fittoapp/activity.html
{% extends 'fittoapp/layout.html' %}
{% load static %}

{% block title%} - activity{% endblock %}

{% block link %}
<script defer src="{% static 'fittoapp/activity.js' %}"></script>
<link rel="stylesheet" href="{% static 'fittoapp/styles-activity.css' %}">
<link rel="stylesheet" href="{% static 'fittoapp/styles-calc.css'%}"> 
{% endblock %}

{% block body%}
    <h1 id="title">Add exercise</h1>

    <fieldset class="main-input">
        <form>
            <label for="food-input">
                <input type="text" name="food-input" id="food-input" autocomplete="off" placeholder="Enter activities performed">
            </label>
            <button id="calculate-btn" type="button">calculate</button>
        </form>
    </fieldset>
    <div class="table_container">
        <table class="boostrap4_dark">
            
        </table>
    </div>

    <dialog class="modal" id="modal">
        
        <div class="dialogTitle"> 
            <span id="foodTitleDialog"></span>
            <button id="closeButton">&times;</button>
        </div>
        <div class="box-burned">
            <form class="formserving form-burned">
                <label for="effotLevel">Effort Level:
                    <span id="effortlevel"></span>
                </label>
                <label for="duration">Duration:
                    <input type="text" name="duration" id="duration" value=""> Min
                </label>
                <label for="energyBurned">Energy Burned: 
                    <input type="text" name="energyBurned" id="energyBurned"> Kcal
                </label>
            </form>
        </div>
            <div class="dialogaddFood">
                <button class="btn-addFood" id="btn-dialogAddFood" type="button">Add Exercise</button>
            </div>
    </dialog>

    <script>
        const csrftoken = '{{ csrf_token }}'
    </script>
{% endblock %}

main/fittoapp/templates/fittoapp/calc.html
{% extends 'fittoapp/layout.html' %}
{% load static %}

    {% block title%} - calc{% endblock%}
    {% block link %}
    <link rel="stylesheet" href="{% static 'fittoapp/styles-calc.css'%}"> 
    <script defer src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script defer src="{% static 'fittoapp/calculate.js'%}"></script>
    {% endblock %}

    {% block body %}
    <h1 id="title">calculate your calories - the easy way.</h1>

    <fieldset class="main-input">
        <form>
            <label for="food-input">
                <input type="text" name="food-input" id="food-input" autofocus="on" autocomplete="off" placeholder="Enter what you ate today">
            </label>
            <button id="calculate-btn" type="button">calculate</button>
        </form>
    </fieldset>

    

      
        <div class="table_container">
            <table class="boostrap4_dark">
                
            </table>
        </div>
       
        <dialog class="modal" id="modal" role="dialog" aria-modal="true">
        
            <div class="dialogTitle"> 
                <span id="foodTitleDialog"></span>
                <button id="closeButton">&times;</button>
            </div>
            <div class="nutrition-summary">
                <div class="box">
                <div class="chartDiv">
                    <canvas id="myChart" width="20%" height="20%"></canvas>
                </div>
                <div class="nutrition-amounts">
                    <ul class="macrolist">
                        <li><span class="dot" id="roundProtein"></span class="macronutrient" style="color: white;">Protein: <span id="proteinAmt"></span> <span class="percInline">(<span id="percProtein"></span>)</li>
                        <li><span class="dot" id="roundcarbs"></span class="macronutrient">Carbs: <span id="carbsAmt"></span> <span id="percInline">(<span id="percCarbs"></span></span>)</li>
                        <li><span class="dot" id="roundfat"></span class="macronutrient">Fat: <span id="fatAmt"></span> <span id="percInline"></span>(<span id="percFat"></span>)</li>
                    </ul>
                </div>
                </div>

                <div class="box2">
                    <form class="formserving">
                        <label for="timeofday">Time of Meal: 
                            <select name="timeofday" id="timeofday">
                                <option value="Breakfast">Breakfast</option>
                                <option value="Lunch">Lunch</option>
                                <option value="Snack">Snack</option>
                                <option value="Dinner">Dinner</option>
                            </select>
                        </label>
                        <label for="serving">Serving Size
                            <input type="text" name="serving" value="1" id="serving">
                            <select name="servingtype" id="servingtype">
                            </select>
                        </label>
                    </form>
                </div>
            </div>
            <div class="dialogaddFood">
                <button class="btn-addFood" id="btn-dialogAddFood" type="button">Add Food</button>
            </div>
        </dialog>
       
    <script>
        const csrftoken = '{{ csrf_token }}'
    </script>
    {% endblock %}

main/fittoapp/templates/fittoapp/index.html
{% extends 'fittoapp/layout.html' %}
{% load static %}

    {% block title %} - Home{% endblock %}
    {% block link%}
    <link rel="stylesheet" href="{% static 'fittoapp/styles.css'%}">
    <link rel="stylesheet" href="{% static 'fittoapp/index.css'%}">
    <script src="https://kit.fontawesome.com/156d77620b.js" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script defer src="{% static 'fittoapp/index.js'%}"></script>
    {% endblock %}
    {% block body %}
    <div class="container">
        <div class="rectangle-parent">
            
            <div class="frame-item"></div>
            <div class="your-progress">Your Progress</div>
            <div class="frame-inner"></div>
            <div class="avg-calories">Avg Calories</div>
            <b class="kcal"></b>
            <img class="vector-icon" alt="" src="{% static 'fittoapp/public/bowl-rice-solid.svg' %}" />
            
      
            <div class="rectangle-div"></div>
            <div class="avg-carbs">Avg Carbs</div>
            <div class="avg-fat">Avg Fat</div>
            <div class="avg-protein">Avg Protein</div>
            <div class="avg-fiber">Avg Fiber</div>
            <div class="gm"></div>
            <div class="gm1"></div>
            <div class="gm2"></div>
            <div class="gm3"></div>
            <img class="vector-icon1" alt="" src="{% static 'fittoapp/public/cubes-stacked-solid.svg' %}" />
      
            <img class="vector-icon2" alt="" src="{% static 'fittoapp/public/shrimp-solid.svg' %}" />
      
            <img class="vector-icon3" alt="" src="{% static 'fittoapp/public/wheat-awn-solid.svg' %}" />
      
            <img class="vector-icon4" alt="" src="{% static 'fittoapp/public/jar-solid.svg' %}" />
      
            <div class="frame-child1"></div>
            <div class="frame-child2">
                <canvas id="progressChart"></canvas>
            </div>
            <div class="frame-child3"></div>
            <div class="breakfast">Breakfast</div>
            <div class="dinner">Dinner</div>
            <div class="lunch">Lunch</div>
            <img class="group-icon" alt="" src="{% static 'fittoapp/public/breakfast-svgrepo-com.svg' %}" /> 
            <img class="group-icon1" alt="" src="{% static 'fittoapp/public/lunch-svgrepo-com.svg' %}" /> 
            <img class="group-icon2" alt="" src="{% static 'fittoapp/public/dinner-svgrepo-com.svg' %}" /> 
            <div class="br1"></div>
            <div class="br2"></div>
            <div class="br3"></div>

          </div>
        <div class="summary-container">
            <div class="calorie-summary">
                <div id="chartContainer">
                    <div id="calorieChartDiv">
                        <canvas id="calorieChart"></canvas>
                    </div>
                    <div id="calorieBurnedChartDiv">
                        <canvas id="calorieBurnedChart"></canvas>
                    </div>
                    <div id="calorieRemainingChartDiv">
                        <canvas id="calorieRemainingChart"></canvas>
                    </div>
                    <div class="charttext">
                        <span id="consumed">Consumed</span>
                        <span id="burned">Burned</span>
                        <span id="remaining">Remaining</span>
                    </div>
                </div>
            </div>
            <div class="macronutrients-summary">
                <div id="macroBarChartDiv">
                    <span class="macro-progress-name">Energy</span>
                    
                    <div class="progressbar">
                        <span class="macro-per" id="energyprogress"> 
                            <span class="tooltip" id="energytooltip"></span>
                            <span id="energynumbers"></span>
                        </span>
                        
                    </div>
                </div>
                <div id="macroBarChartDiv">
                    <span class="macro-progress-name">Protein</span>
                    
                    <div class="progressbar">
                        <span class="macro-per" id="proteinprogress">
                            <span class="tooltip" id="proteintooltip"></span>
                            <span id="proteinnumbers"></span>
                        </span>
                        
                    </div>
                </div>
                <div id="macroBarChartDiv">
                    <span class="macro-progress-name">Carbs</span>
                    
                    <div class="progressbar">
                        <span class="macro-per" id="carbsprogress">
                            <span class="tooltip" id="carbstooltip"></span>
                            <span id="carbsnumbers"></span>
                        </span>
                        
                    </div>
                </div>
                <div id="macroBarChartDiv">
                    <span class="macro-progress-name">Fat</span>
                    
                    <div class="progressbar">
                        <span class="macro-per" id="fatprogress">
                            <span class="tooltip" id="fattooltip"></span>
                            <span id="fatnumbers"></span>
                        </span>
                    </div>
                </div>
             </div>
            </div>
        </div>
    </div>    

    <script>
        const food_data = JSON.parse('{{ food_data | safe }}')
        const bmr_data = JSON.parse('{{ bmr_data | safe}}')
        const avg_data = JSON.parse('{{ avg_data | safe }}')
        const food_data_energy = JSON.parse('{{ food_data_energy | safe}}')
        const food_data_date = JSON.parse('{{ food_data_date | safe}}')
        const activity_data = JSON.parse('{{ activity_data | safe }}')
    
    </script>
    {% endblock %}

main/fittoapp/templates/fittoapp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fitto {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'fittoapp/styles.css' %}">
    
    {% block link %} {% endblock %}
</head>
<body>
    <nav>
        
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'fittoapp:index' %}" aria-current="page">home</a>
            </li>
            <li>
                <a href="{% url 'fittoapp:calorie' %}">calorie-calculator</a>
            </li>
            <li>
                <a href="/activity">activity-tracker</a>
            </li>
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
        </ul>
            {% else %}
        <ul>
            <li>
                <a href="{% url 'register' %}" aria-current="page">Register</a>
            </li>
            <li>
                <a href="{% url 'login' %}" aria-current="page">Login</a>
            </li>
        </ul>
            {% endif %}
    </nav>
    {% if messages %}
     {% for message in messages %}
        <div class='django-messages'>
            {{ message }}
        </div>
     {% endfor %}
    {% endif %}
    {% block body %}

    {% endblock %}
</body>
</html>